import React, { useState, useEffect, useCallback } from 'react'
import { FiSearch, FiX, FiPlus, FiEye, FiCheck, FiSend, FiPrinter, FiMail } from 'react-icons/fi'
import { listInvoices, createInvoice, markInvoiceSent, markInvoicePaid, emailInvoice } from '../services/invoiceService'
import useAuth from '../hooks/useAuth'

const COMPANY = 'SupplySphere'

// ── Open a printable invoice in a new window and trigger the print dialog ──
function printInvoice(inv) {
  const w = window.open('', '_blank', 'width=820,height=1040')
  if (!w) { alert('Please allow pop-ups to print the invoice.'); return }
  const money = n => '₹' + Number(n || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  const date = d => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'
  const lines = [
    ['Subtotal', inv.subtotal],
    ['CGST', inv.cgst_amount],
    ['SGST', inv.sgst_amount],
    ['IGST', inv.igst_amount],
    ['Discount', inv.discount_amount ? -Math.abs(Number(inv.discount_amount)) : 0],
  ].filter(([, v]) => Number(v) !== 0)
  const lineRows = lines.map(([l, v]) => `<tr><td>${l}</td><td class="r">${money(v)}</td></tr>`).join('')
  const due = Number(inv.amount_due)
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${inv.invoice_number}</title>
<style>
  *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;color:#172B4D;margin:0;padding:40px;font-size:13px}
  .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #0052CC;padding-bottom:16px}
  .brand{font-size:24px;font-weight:800;color:#0052CC} .doctype{font-size:12px;color:#5E6C84;letter-spacing:.08em;text-transform:uppercase}
  .invno{font-size:18px;font-weight:700;text-align:right} .status{display:inline-block;margin-top:4px;padding:2px 10px;border-radius:3px;font-size:11px;font-weight:700;text-transform:uppercase;background:#DEEBFF;color:#0747A6}
  .cols{display:flex;justify-content:space-between;gap:32px;margin:28px 0}
  .col h4{margin:0 0 6px;font-size:11px;color:#5E6C84;text-transform:uppercase;letter-spacing:.06em} .col div{line-height:1.5}
  .meta{margin-left:auto;text-align:right} .meta div{margin-bottom:4px} .meta span{color:#5E6C84;margin-right:8px}
  table{width:100%;border-collapse:collapse;margin-top:8px} td{padding:7px 0;border-bottom:1px solid #EBECF0} .r{text-align:right;font-family:monospace}
  .total td{border-top:2px solid #172B4D;border-bottom:none;font-weight:700;font-size:15px;padding-top:12px}
  .due{color:${due > 0 ? '#DE350B' : '#00875A'};font-weight:700}
  .notes{margin-top:24px;padding:12px 16px;background:#F4F5F7;border-radius:6px;color:#42526E}
  .foot{margin-top:40px;padding-top:16px;border-top:1px solid #DFE1E6;font-size:11px;color:#97A0AF;text-align:center}
  @media print{body{padding:24px}}
</style></head><body>
  <div class="head">
    <div><div class="brand">${COMPANY}</div><div class="doctype">Tax Invoice</div></div>
    <div><div class="invno">${inv.invoice_number}</div><div style="text-align:right"><span class="status">${inv.status || 'draft'}</span></div></div>
  </div>
  <div class="cols">
    <div class="col"><h4>Bill To</h4><div><strong>${inv.vendor_name || '—'}</strong></div><div>${inv.vendor_email || ''}</div></div>
    <div class="col meta">
      <div><span>PO Number</span>${inv.po_number || '—'}</div>
      <div><span>Issue Date</span>${date(inv.issue_date)}</div>
      <div><span>Due Date</span>${date(inv.due_date)}</div>
    </div>
  </div>
  <table>
    ${lineRows}
    <tr class="total"><td>Total</td><td class="r">${money(inv.total_amount)}</td></tr>
    <tr><td>Paid</td><td class="r">${money(inv.amount_paid)}</td></tr>
    <tr><td class="due">Amount Due</td><td class="r due">${money(inv.amount_due)}</td></tr>
  </table>
  ${inv.notes ? `<div class="notes"><strong>Notes:</strong> ${inv.notes}</div>` : ''}
  <div class="foot">Generated by ${COMPANY} · ${date(new Date())}</div>
  <script>window.onload=function(){window.focus();window.print();};window.onafterprint=function(){window.close();};</script>
</body></html>`)
  w.document.close()
}

const STATUS = {
  draft:     { bg: '#F4F5F7', color: '#42526E' },
  sent:      { bg: '#DEEBFF', color: '#0747A6' },
  paid:      { bg: '#E3FCEF', color: '#006644' },
  overdue:   { bg: '#FFEBE6', color: '#BF2600' },
  cancelled: { bg: '#FFFAE6', color: '#974F0C' },
}

function Badge({ value }) {
  const s = STATUS[value?.toLowerCase()] || STATUS.draft
  return <span style={{ display: 'inline-flex', padding: '2px 8px', borderRadius: 3, fontSize: 11, fontWeight: 700, letterSpacing: '0.04em', textTransform: 'uppercase', background: s.bg, color: s.color }}>{value}</span>
}

const MOCK = [
  { id: 1, invoice_number: 'INV-2026-00001', po_number: 'PO-2026-00001', vendor_name: 'Tech Core LTD', total_amount: '140000.00', amount_paid: '140000.00', amount_due: '0.00', status: 'paid', issue_date: '2026-06-05', due_date: '2026-07-05', created_at: '2026-06-05T10:00:00Z' },
  { id: 2, invoice_number: 'INV-2026-00002', po_number: 'PO-2026-00002', vendor_name: 'OfficeZone Furniture', total_amount: '87000.00', amount_paid: '0.00', amount_due: '87000.00', status: 'sent', issue_date: '2026-06-06', due_date: '2026-07-06', created_at: '2026-06-06T09:00:00Z' },
  { id: 3, invoice_number: 'INV-2026-00003', po_number: 'PO-2026-00003', vendor_name: 'Infra Supplies Pvt Ltd', total_amount: '220000.00', amount_paid: '110000.00', amount_due: '110000.00', status: 'overdue', issue_date: '2026-05-01', due_date: '2026-06-01', created_at: '2026-05-01T14:00:00Z' },
]

const TABS = ['all', 'draft', 'sent', 'paid', 'overdue']

function InvoiceDetail({ inv, onClose, onMarkSent, onMarkPaid, canManage }) {
  const [acting, setActing] = useState(null)
  const [msg, setMsg] = useState(null)
  const act = async (fn, label) => {
    setActing(label)
    try { await fn(inv.id); onClose() }
    catch (e) { alert(e.response?.data?.detail || 'Action failed.') }
    finally { setActing(null) }
  }
  const sendEmail = async () => {
    setActing('email'); setMsg(null)
    try {
      const { data } = await emailInvoice(inv.id)
      setMsg({ ok: true, text: data.detail || 'Invoice emailed.' })
    } catch (e) {
      setMsg({ ok: false, text: e.response?.data?.detail || 'Failed to send email.' })
    } finally { setActing(null) }
  }
  return (
    <>
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(9,30,66,0.32)', zIndex: 40 }} />
      <div style={{ position: 'fixed', right: 0, top: 0, bottom: 0, width: 460, background: 'var(--bg-white)', zIndex: 50, boxShadow: '-4px 0 24px rgba(9,30,66,0.15)', display: 'flex', flexDirection: 'column', fontFamily: 'var(--font)' }}>
        <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700 }}>{inv.invoice_number}</div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2 }}>{inv.vendor_name}</div>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}><FiX size={18} /></button>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: 16 }}>
          <Badge value={inv.status} />
          {/* Amounts */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
            {[['Total', inv.total_amount], ['Paid', inv.amount_paid], ['Due', inv.amount_due]].map(([l, v]) => (
              <div key={l} style={{ padding: '12px', background: 'var(--bg)', borderRadius: 6, border: '1px solid var(--border-light)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{l}</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: Number(v) > 0 && l === 'Due' ? 'var(--danger)' : 'var(--text-dark)', marginTop: 4 }}>₹{Number(v).toLocaleString('en-IN')}</div>
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {[
              ['PO Number', inv.po_number || '—'],
              ['Vendor', inv.vendor_name || '—'],
              ['Email', inv.vendor_email || '—'],
              ['Issue Date', inv.issue_date ? new Date(inv.issue_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'],
              ['Due Date', inv.due_date ? new Date(inv.due_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'],
            ].map(([l, v]) => (
              <div key={l} style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}>
                <span style={{ fontSize: 12, color: 'var(--text-muted)', flexShrink: 0 }}>{l}</span>
                <span style={{ fontSize: 13, color: 'var(--text-dark)' }}>{v}</span>
              </div>
            ))}
          </div>
          {inv.notes && (
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 6 }}>Notes</div>
              <div style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.6 }}>{inv.notes}</div>
            </div>
          )}
        </div>
        <div style={{ padding: '16px 24px', borderTop: '1px solid var(--border)', display: 'flex', flexDirection: 'column', gap: 10 }}>
          {msg && (
            <div style={{ padding: '8px 12px', borderRadius: 'var(--radius-md)', fontSize: 12.5, background: msg.ok ? 'var(--success-bg)' : 'var(--danger-bg)', color: msg.ok ? 'var(--success)' : 'var(--danger)' }}>{msg.text}</div>
          )}
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <button onClick={() => printInvoice(inv)} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 16px', background: 'var(--bg-white)', border: '1.5px solid var(--border)', borderRadius: 'var(--radius-md)', color: 'var(--text-dark)', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' }}>
              <FiPrinter size={13} /> Print
            </button>
            {canManage && (
              <button onClick={sendEmail} disabled={acting === 'email'} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 16px', background: 'var(--bg-white)', border: '1.5px solid var(--primary)', borderRadius: 'var(--radius-md)', color: 'var(--primary)', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)', opacity: acting === 'email' ? 0.7 : 1 }}>
                <FiMail size={13} /> {acting === 'email' ? 'Sending…' : 'Email Vendor'}
              </button>
            )}
            {canManage && inv.status === 'draft' && (
              <button onClick={() => act(markInvoiceSent, 'sent')} disabled={acting === 'sent'} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 16px', background: 'var(--primary)', border: 'none', borderRadius: 'var(--radius-md)', color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' }}>
                <FiSend size={13} /> Mark Sent
              </button>
            )}
            {canManage && inv.status === 'sent' && (
              <button onClick={() => act(markInvoicePaid, 'paid')} disabled={acting === 'paid'} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 16px', background: '#00875A', border: 'none', borderRadius: 'var(--radius-md)', color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' }}>
                <FiCheck size={13} /> Mark Paid
              </button>
            )}
          </div>
        </div>
      </div>
    </>
  )
}

function CreateInvoiceModal({ onClose, onCreated }) {
  const [form, setForm] = useState({ po_id: '', issue_date: '', due_date: '', subtotal: '', cgst_amount: '0', sgst_amount: '0', igst_amount: '0', discount_amount: '0', notes: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  const handleSubmit = async () => {
    if (!form.po_id || !form.issue_date || !form.due_date || !form.subtotal) { setError('PO ID, Issue Date, Due Date, and Subtotal are required.'); return }
    setLoading(true)
    try {
      await createInvoice({
        po_id: parseInt(form.po_id),
        issue_date: form.issue_date,
        due_date: form.due_date,
        subtotal: parseFloat(form.subtotal),
        cgst_amount: parseFloat(form.cgst_amount) || 0,
        sgst_amount: parseFloat(form.sgst_amount) || 0,
        igst_amount: parseFloat(form.igst_amount) || 0,
        discount_amount: parseFloat(form.discount_amount) || 0,
        notes: form.notes,
      })
      onCreated()
    } catch (err) {
      setError(err.response?.data?.detail || 'Failed to create invoice.')
    } finally { setLoading(false) }
  }

  const inp = (label, key, type = 'text', placeholder = '') => (
    <div>
      <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-dark)', marginBottom: 5 }}>{label}</label>
      <input type={type} value={form[key]} onChange={e => set(key, e.target.value)} placeholder={placeholder} style={{ width: '100%', padding: '8px 12px', fontSize: 13, border: '1.5px solid var(--border)', borderRadius: 'var(--radius-md)', fontFamily: 'var(--font)', outline: 'none', boxSizing: 'border-box' }} />
    </div>
  )

  return (
    <>
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(9,30,66,0.5)', zIndex: 60 }} />
      <div style={{ position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', width: 520, maxHeight: '88vh', overflowY: 'auto', background: 'var(--bg-white)', borderRadius: 'var(--radius-xl)', zIndex: 70, boxShadow: '0 20px 60px rgba(9,30,66,0.35)', fontFamily: 'var(--font)' }}>
        <div style={{ padding: '18px 24px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', position: 'sticky', top: 0, background: 'var(--bg-white)', zIndex: 1 }}>
          <h2 style={{ margin: 0, fontSize: 15, fontWeight: 700, color: 'var(--text-dark)' }}>Create Invoice</h2>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}><FiX size={16} /></button>
        </div>
        <div style={{ padding: '20px 24px', display: 'flex', flexDirection: 'column', gap: 12 }}>
          {error && <div style={{ padding: '10px 14px', background: 'var(--danger-bg)', border: '1px solid rgba(222,53,11,.25)', borderRadius: 'var(--radius-md)', color: 'var(--danger)', fontSize: 13 }}>{error}</div>}
          {inp('Purchase Order ID *', 'po_id', 'number', 'Enter PO ID')}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            {inp('Issue Date *', 'issue_date', 'date')}
            {inp('Due Date *', 'due_date', 'date')}
          </div>
          {inp('Subtotal (₹) *', 'subtotal', 'number', '0.00')}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            {inp('CGST (₹)', 'cgst_amount', 'number', '0.00')}
            {inp('SGST (₹)', 'sgst_amount', 'number', '0.00')}
            {inp('IGST (₹)', 'igst_amount', 'number', '0.00')}
            {inp('Discount (₹)', 'discount_amount', 'number', '0.00')}
          </div>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-dark)', marginBottom: 5 }}>Notes</label>
            <textarea value={form.notes} onChange={e => set('notes', e.target.value)} rows={3} style={{ width: '100%', padding: '8px 12px', fontSize: 13, border: '1.5px solid var(--border)', borderRadius: 'var(--radius-md)', fontFamily: 'var(--font)', outline: 'none', resize: 'vertical', boxSizing: 'border-box' }} />
          </div>
        </div>
        <div style={{ padding: '14px 24px', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'flex-end', gap: 10 }}>
          <button onClick={onClose} style={{ padding: '9px 20px', border: '1.5px solid var(--border)', borderRadius: 'var(--radius-md)', background: 'none', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' }}>Cancel</button>
          <button onClick={handleSubmit} disabled={loading} style={{ padding: '9px 20px', background: 'var(--primary)', border: 'none', borderRadius: 'var(--radius-md)', color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)', opacity: loading ? 0.7 : 1 }}>
            {loading ? 'Creating…' : 'Create Invoice'}
          </button>
        </div>
      </div>
    </>
  )
}

export default function Invoices() {
  const { hasPermission } = useAuth()
  const canView = hasPermission('view_invoices')
  const canManage = hasPermission('create_po')

  const [invoices, setInvoices] = useState([])
  const [loading, setLoading] = useState(true)
  const [tab, setTab] = useState('all')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState(null)
  const [showCreate, setShowCreate] = useState(false)

  const fetch = useCallback(async () => {
    setLoading(true)
    try {
      const { data } = await listInvoices()
      setInvoices(Array.isArray(data) ? data : data.results || [])
    } catch { setInvoices(MOCK) }
    finally { setLoading(false) }
  }, [])

  useEffect(() => { fetch() }, [fetch])

  const filtered = invoices.filter(i => {
    const matchTab = tab === 'all' || i.status === tab
    const matchSearch = !search || (i.invoice_number || '').toLowerCase().includes(search.toLowerCase()) || (i.vendor_name || '').toLowerCase().includes(search.toLowerCase())
    return matchTab && matchSearch
  })
  const countFor = t => t === 'all' ? invoices.length : invoices.filter(i => i.status === t).length

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16, fontFamily: 'var(--font)' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: 'var(--text-dark)' }}>Invoices</h1>
          <p style={{ margin: '3px 0 0', fontSize: 13, color: 'var(--text-muted)' }}>Track vendor invoices and payment status</p>
        </div>
        {canManage && (
          <button onClick={() => setShowCreate(true)} style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '9px 18px', background: 'var(--primary)', color: '#fff', border: 'none', borderRadius: 'var(--radius-md)', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' }}>
            <FiPlus size={15} /> New Invoice
          </button>
        )}
      </div>
      <div style={{ background: 'var(--bg-white)', border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)', overflow: 'hidden' }}>
        <div style={{ display: 'flex', padding: '0 16px', borderBottom: '1px solid var(--border)', gap: 2 }}>
          {TABS.map(t => (
            <button key={t} onClick={() => setTab(t)} style={{ padding: '12px 14px', background: 'none', border: 'none', cursor: 'pointer', fontSize: 13, fontWeight: tab === t ? 700 : 500, color: tab === t ? 'var(--primary)' : 'var(--text-muted)', borderBottom: tab === t ? '2px solid var(--primary)' : '2px solid transparent', fontFamily: 'var(--font)', textTransform: 'capitalize' }}>
              {t.charAt(0).toUpperCase() + t.slice(1)} <span style={{ fontSize: 11, marginLeft: 4, background: tab === t ? 'var(--primary-light)' : 'var(--bg)', color: tab === t ? 'var(--primary)' : 'var(--text-muted)', padding: '1px 6px', borderRadius: 10, fontWeight: 700 }}>{countFor(t)}</span>
            </button>
          ))}
        </div>
        <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-light)' }}>
          <div style={{ position: 'relative', maxWidth: 340 }}>
            <FiSearch size={14} style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search invoices…" style={{ width: '100%', padding: '8px 12px 8px 32px', fontSize: 13, border: '1.5px solid var(--border)', borderRadius: 'var(--radius-md)', fontFamily: 'var(--font)', outline: 'none', background: 'var(--bg)', boxSizing: 'border-box' }} />
          </div>
        </div>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: 'var(--bg-subtle)', borderBottom: '2px solid var(--border)' }}>
              {['Invoice #', 'Vendor', 'Total', 'Amount Due', 'Status', 'Due Date', ''].map(h => (
                <th key={h} style={{ padding: '9px 16px', textAlign: 'left', fontSize: 11, fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', whiteSpace: 'nowrap' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={7} style={{ padding: '32px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>Loading…</td></tr>
            ) : filtered.length === 0 ? (
              <tr><td colSpan={7} style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>No invoices found</td></tr>
            ) : filtered.map((inv, idx) => (
              <tr key={inv.id} onClick={() => setSelected(inv)} style={{ borderBottom: idx < filtered.length - 1 ? '1px solid var(--border-light)' : 'none', cursor: 'pointer', transition: 'background .1s' }}
                onMouseEnter={e => e.currentTarget.style.background = 'var(--bg)'}
                onMouseLeave={e => e.currentTarget.style.background = ''}
              >
                <td style={{ padding: '12px 16px', fontSize: 13, fontWeight: 600, color: 'var(--primary)' }}>{inv.invoice_number}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, color: 'var(--text-dark)' }}>{inv.vendor_name || '—'}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, fontFamily: 'monospace' }}>₹{Number(inv.total_amount).toLocaleString('en-IN')}</td>
                <td style={{ padding: '12px 16px', fontSize: 13, fontFamily: 'monospace', color: Number(inv.amount_due) > 0 ? 'var(--danger)' : 'var(--success)', fontWeight: 700 }}>₹{Number(inv.amount_due).toLocaleString('en-IN')}</td>
                <td style={{ padding: '12px 16px' }}><Badge value={inv.status} /></td>
                <td style={{ padding: '12px 16px', fontSize: 12.5, color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>{inv.due_date ? new Date(inv.due_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}</td>
                <td style={{ padding: '12px 16px' }}>
                  <button style={{ color: 'var(--primary)', background: 'none', border: 'none', cursor: 'pointer' }} onClick={e => { e.stopPropagation(); setSelected(inv) }}><FiEye size={14} /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {selected && <InvoiceDetail inv={selected} onClose={() => { setSelected(null); fetch() }} onMarkSent={markInvoiceSent} onMarkPaid={markInvoicePaid} canManage={canManage} />}
      {showCreate && <CreateInvoiceModal onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); fetch() }} />}
    </div>
  )
}
